version: '3.8'

services:
  rethinkdb:
    image: rethinkdb:latest
    environment:
      - RETHINKDB_DB=${RETHINKDB_DB}
      - RETHINKDB_VIEW_PORT=${RETHINKDB_VIEW_PORT}
      - RETHINKDB_UI_VIEW_PORT=${RETHINKDB_UI_VIEW_PORT}
    restart: unless-stopped
    ports:
      - "${RETHINKDB_VIEW_PORT}:28015"
      - "${RETHINKDB_UI_VIEW_PORT}:8080"
    volumes:
      - rethinkdb_data:/data:rw

  llm_bot_backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    # restart: on-failure
    ports:
      - "${SGI_PORT}:${SGI_PORT}"
    volumes:
      - ./src:/opt/app-root/src:rw
      - ./LOGS:/LOGS:rw
      - ./config.yaml:/opt/app-root/config.yaml:ro

    command: ["gunicorn", "-c", "/opt/app-root/src/api/config/gunicorn.conf.py", "src.api.application:app"]

volumes:
  rethinkdb_data:
    external: false
